const { createClient } = require('@supabase/supabase-js');

// Config from project
const supabaseUrl = "https://paxnqyuzuxgktqlnlqxi.supabase.co";
// Using the service role key to bypass RLS
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBheG5xeXV6dXhna3RxbG5scXhpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzU4NzM5MCwiZXhwIjoyMDgzMTYzMzkwfQ.VSmepQhDLt5qoy0QsLgOCXiSokJFBWXtwuNelBZAlMU";

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

const products = [
    {
        title: "The Art of Code",
        author: "Douglas Crockford",
        isbn: "978-0596517748",
        price: 29.99,
        category: "technology",
        subcategory: "programming",
        description: "A comprehensive guide to writing beautiful, maintainable code. Perfect for developers of all levels.",
        image_url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 50,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Urban Photography Essentials",
        author: "Steve McCurry",
        isbn: "978-0714845587",
        price: 45.00,
        category: "art",
        subcategory: "photography",
        description: "Master the streets with this guide to urban photography. Includes tips on lighting, composition, and post-processing.",
        image_url: "https://images.unsplash.com/photo-1552168324-d612d77725e3?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 25,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Minimalist Living",
        author: "Joshua Fields Millburn",
        isbn: "978-0615579937",
        price: 19.95,
        category: "lifestyle",
        subcategory: "general",
        description: "Declutter your life and find peace in simplicity. A practical guide to minimalism in the modern world.",
        image_url: "https://images.unsplash.com/photo-1491336477066-31156b5e4f35?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 100,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Advanced React Patterns",
        author: "Kent C. Dodds",
        isbn: "978-1492053535",
        price: 55.00,
        category: "technology",
        subcategory: "programming",
        description: "Deep dive into advanced React patterns, hooks, and performance optimization techniques.",
        image_url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 30,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "The History of Modern Design",
        author: "Raizman David",
        isbn: "978-1856693486",
        price: 75.00,
        category: "art",
        subcategory: "design",
        description: "A visual journey through the evolution of design from the 20th century to today.",
        image_url: "https://images.unsplash.com/photo-1505330622279-bf7d7fc918f4?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 15,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Sustainable Gardening",
        author: "Monty Don",
        isbn: "978-1405316733",
        price: 24.50,
        category: "lifestyle",
        subcategory: "gardening",
        description: "Grow your own food and create a beautiful garden using sustainable and organic practices.",
        image_url: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 60,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Machine Learning for Beginners",
        author: "Andrew Ng",
        isbn: "978-0062456027",
        price: 39.99,
        category: "technology",
        subcategory: "ai",
        description: "An intro guide to ML concepts without the complex math. Start building models today.",
        image_url: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 40,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Abstract Art Techniques",
        author: "Wassily Kandinsky",
        isbn: "978-0486202479",
        price: 32.00,
        category: "art",
        subcategory: "painting",
        description: "Explore the freedom of abstract expressionism. Learn various techniques to create stunning abstract art.",
        image_url: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 20,
        featured: true,
        created_at: new Date().toISOString()
    },

    {
        title: "Smartbrains Pre-Primary Activities PP1",
        author: "Educational Publishers Board",
        isbn: "978-9966-14-100-1",
        price: 450.00,
        category: "cbc",
        subcategory: "pre-primary",
        grade_level: "pp1",
        curriculum: "cbc",
        description: "Integrated learning activities for PP1 covering language, mathematical, environmental, and psychomotor skills.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 125,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Longhorn Early Years Learning Activities PP2",
        author: "Longhorn Publishers",
        isbn: "978-9966-14-100-2",
        price: 480.00,
        category: "cbc",
        subcategory: "pre-primary",
        grade_level: "pp2",
        curriculum: "cbc",
        description: "Comprehensive activity book for PP2 students following CBC curriculum guidelines.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 110,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Mentor Literacy Activities Grade 1",
        author: "Mentor Publishing",
        isbn: "978-9966-14-200-1",
        price: 520.00,
        category: "cbc",
        subcategory: "lower-primary",
        grade_level: "grade-1-3",
        curriculum: "cbc",
        description: "Literacy activities integrating Kiswahili and English for Grade 1 students.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 200,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Spotlight Environmental Activities Grade 2",
        author: "Spotlight Publishers",
        isbn: "978-9966-14-200-3",
        price: 510.00,
        category: "cbc",
        subcategory: "lower-primary",
        grade_level: "grade-1-3",
        curriculum: "cbc",
        description: "Environmental activities covering hygiene, science, social studies, and agriculture for Grade 2.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 180,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "KLB Visionary Mathematical Activities Grade 3",
        author: "Kenya Literature Bureau",
        isbn: "978-9966-14-200-5",
        price: 530.00,
        category: "cbc",
        subcategory: "lower-primary",
        grade_level: "grade-1-3",
        curriculum: "cbc",
        description: "Mathematical activities designed for Grade 3 CBC curriculum.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 175,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Mentor CRE Activities Grade 3",
        author: "Mentor Publishing",
        isbn: "978-9966-14-200-7",
        price: 350.00,
        category: "cbc",
        subcategory: "religious",
        grade_level: "grade-1-3",
        curriculum: "cbc",
        description: "Christian Religious Education activities for Grade 3 students.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 220,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Spotlight Science and Technology Grade 4",
        author: "Spotlight Publishers",
        isbn: "978-9966-14-300-1",
        price: 680.00,
        category: "cbc",
        subcategory: "middle-school",
        grade_level: "grade-4-6",
        curriculum: "cbc",
        description: "Science and Technology textbook for Grade 4 following CBC curriculum.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 190,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "OUP New Progressive Mathematics Grade 5",
        author: "Oxford University Press",
        isbn: "978-9966-14-300-3",
        price: 720.00,
        category: "cbc",
        subcategory: "middle-school",
        grade_level: "grade-4-6",
        curriculum: "cbc",
        description: "Mathematics textbook for Grade 5 with progressive learning approach.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 165,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Our Lives Today Social Studies Grade 6",
        author: "Oxford University Press",
        isbn: "978-9966-14-300-5",
        price: 650.00,
        category: "cbc",
        subcategory: "middle-school",
        grade_level: "grade-4-6",
        curriculum: "cbc",
        description: "Social Studies covering Geography, History, and Civics for Grade 6.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 155,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Mentor Agriculture Grade 6",
        author: "Mentor Publishing",
        isbn: "978-9966-14-300-7",
        price: 620.00,
        category: "cbc",
        subcategory: "middle-school",
        grade_level: "grade-4-6",
        curriculum: "cbc",
        description: "Agriculture textbook for Grade 6 with practical activities and illustrations.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 140,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "KLB Top Scholar Integrated Science Grade 7",
        author: "Kenya Literature Bureau",
        isbn: "978-9966-14-400-1",
        price: 850.00,
        category: "cbc",
        subcategory: "junior-school",
        grade_level: "grade-7-9",
        curriculum: "cbc",
        description: "Integrated Science textbook for Grade 7 Junior School students.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 210,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Mentor Business Studies Grade 8",
        author: "Mentor Publishing",
        isbn: "978-9966-14-400-3",
        price: 780.00,
        category: "cbc",
        subcategory: "junior-school",
        grade_level: "grade-7-9",
        curriculum: "cbc",
        description: "Business Studies textbook introducing basic business concepts for Grade 8.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 185,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "KLB Top Scholar Social Studies Grade 9",
        author: "Kenya Literature Bureau",
        isbn: "978-9966-14-400-5",
        price: 820.00,
        category: "cbc",
        subcategory: "junior-school",
        grade_level: "grade-7-9",
        curriculum: "cbc",
        description: "Social Studies textbook covering citizenship, geography, and history for Grade 9.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 175,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Mentor Computer Science Grade 9",
        author: "Mentor Publishing",
        isbn: "978-9966-14-400-7",
        price: 890.00,
        category: "cbc",
        subcategory: "junior-school",
        grade_level: "grade-7-9",
        curriculum: "cbc",
        description: "Computer Science optional subject textbook for Grade 9 students.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 120,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Secondary Mathematics Form 3",
        author: "KLB Authors",
        isbn: "978-9966-14-500-1",
        price: 950.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Mathematics textbook for Form 3 following the 8-4-4 curriculum.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 160,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Chemistry Today Form 3",
        author: "M. O. Okoth",
        isbn: "978-9966-14-500-3",
        price: 1050.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Chemistry textbook for Form 3 students with practical experiments and exercises.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 145,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Physics Form 3",
        author: "G. N. N. Njoroge & P. K. R. Muriithi",
        isbn: "978-9966-14-500-5",
        price: 1100.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Comprehensive Physics textbook covering Form 3 syllabus with diagrams and examples.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 130,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Biology Today Form 3",
        author: "C. Mwangi",
        isbn: "978-9966-14-500-7",
        price: 980.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Biology textbook for Form 3 with detailed illustrations and study questions.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 155,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Certificate Geography Form 3",
        author: "I. M. I. Gichuhi et al.",
        isbn: "978-9966-14-500-9",
        price: 920.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Geography textbook covering physical and human geography for Form 3.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 140,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Head Start Secondary English Form 4",
        author: "OUP Authors",
        isbn: "978-9966-14-600-1",
        price: 880.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "English textbook for Form 4 with grammar, comprehension, and literature sections.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 170,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Kiswahili Sanifu Form 4",
        author: "Wallah Bin Wallah",
        isbn: "978-9966-14-600-3",
        price: 760.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Kiswahili textbook with grammar, composition, and set book guides for Form 4.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 165,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "History & Government Form 4",
        author: "Ochieng, Owino, et al.",
        isbn: "978-9966-14-600-5",
        price: 900.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "History and Government textbook covering world history and Kenyan government for Form 4.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 135,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Business Studies Form 4",
        author: "S. M. Githaka et al.",
        isbn: "978-9966-14-600-7",
        price: 870.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Business Studies textbook covering entrepreneurship, accounting, and commerce for Form 4.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 150,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Comprehensive Chemistry Form 4",
        author: "M. M. Patel & R. C. Pathak",
        isbn: "978-9966-14-600-9",
        price: 1150.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Advanced Chemistry textbook for Form 4 with revision questions and practical guides.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 125,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Comprehensive Physics Form 4",
        author: "R. S. N. Pillai",
        isbn: "978-9966-14-601-1",
        price: 1200.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Physics textbook for Form 4 with advanced topics and KCSE preparation questions.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 115,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Exploring Biology Form 4",
        author: "K. K. M. Lugulu",
        isbn: "978-9966-14-601-3",
        price: 1020.00,
        category: "old-curriculum",
        subcategory: "secondary",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Biology textbook for Form 4 with comprehensive coverage of KCSE syllabus.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 140,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Tumbo Lisiloshiba (Set Book)",
        author: "Nassir M. Karama",
        isbn: "978-9966-14-700-1",
        price: 420.00,
        category: "story-books",
        subcategory: "set-books",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Kiswahili set book novel for secondary school literature study.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 240,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Living CRE Form 4",
        author: "OUP CRE Authors",
        isbn: "978-9966-14-601-5",
        price: 680.00,
        category: "old-curriculum",
        subcategory: "religious",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "Christian Religious Education textbook for Form 4 with biblical references and exam questions.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 180,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Islamic Religious Education Form 4",
        author: "M. M. K. Abdulla et al.",
        isbn: "978-9966-14-601-7",
        price: 670.00,
        category: "old-curriculum",
        subcategory: "religious",
        grade_level: "form-3-4",
        curriculum: "8-4-4",
        description: "IRE textbook covering Islamic teachings, history, and practices for Form 4.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 95,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Queenex ECD Readers Level 1",
        author: "Queenex Publishers",
        isbn: "978-9966-14-800-1",
        price: 280.00,
        category: "story-books",
        subcategory: "readers",
        grade_level: "pp1",
        curriculum: "cbc",
        description: "Early childhood development readers for language skills development.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 310,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Storymoja Fun with Stories Grade 2",
        author: "Storymoja Publishers",
        isbn: "978-9966-14-800-3",
        price: 320.00,
        category: "story-books",
        subcategory: "readers",
        grade_level: "grade-1-3",
        curriculum: "cbc",
        description: "Illustrated storybook for Grade 2 students to enhance reading comprehension.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 265,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Longhorn Read-It-Yourself Grade 4",
        author: "Longhorn Publishers",
        isbn: "978-9966-14-800-5",
        price: 350.00,
        category: "story-books",
        subcategory: "readers",
        grade_level: "grade-4-6",
        curriculum: "cbc",
        description: "Graded readers for Grade 4 students to encourage independent reading.",
        image_url: "https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80",
        status: "active",
        stock_quantity: 230,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "HB Graphite Pencils (Pack of 12)",
        author: "Staedtler",
        isbn: "STD-PENCIL-HB12-2024",
        price: 180.00,
        category: "stationery",
        subcategory: "writing",
        description: "Premium HB graphite pencils for writing and drafting. Standard school requirement.",
        image_url: "/images/products/stationery/hb_pencils.png",
        status: "active",
        stock_quantity: 450,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Blue Ballpoint Pens (Pack of 10)",
        author: "Bic",
        isbn: "BIC-BP-BLUE10-2024",
        price: 250.00,
        category: "stationery",
        subcategory: "writing",
        description: "Smooth-writing blue ballpoint pens with medium point for everyday school use.",
        image_url: "/images/products/stationery/blue_pens.png",
        status: "active",
        stock_quantity: 380,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Red Marking Pens (Pack of 5)",
        author: "Pilot",
        isbn: "PLT-MARK-RED5-2024",
        price: 320.00,
        category: "stationery",
        subcategory: "writing",
        description: "Red ink pens for teachers' marking and corrections. Quick-drying ink.",
        image_url: "/images/products/stationery/red_pens.png",
        status: "active",
        stock_quantity: 220,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Standard Stapler with 1000 Staples",
        author: "Swingline",
        isbn: "SWG-STA-001-2024",
        price: 850.00,
        category: "stationery",
        subcategory: "office",
        description: "Durable office stapler with built-in staple remover. Includes 1000 standard staples.",
        image_url: "/images/products/stationery/stapler.png",
        status: "active",
        stock_quantity: 75,
        featured: false,
        created_at: new Date().toISOString()
    },

    // ====== WRITING BOOKS & PAPER ======
    {
        title: "A4 Exercise Books (96 pages)",
        author: "Classmate",
        isbn: "CLS-A4-96-2024",
        price: 85.00,
        category: "stationery",
        subcategory: "notebooks",
        description: "Standard A4 exercise book with 96 pages, single line, for daily school work.",
        image_url: "/images/products/stationery/exercise_books.png",
        status: "active",
        stock_quantity: 1200,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "A5 Drawing Books (40 pages)",
        author: "Classmate",
        isbn: "CLS-A5-DRW40-2024",
        price: 120.00,
        category: "stationery",
        subcategory: "art",
        description: "A5 drawing book with blank pages for art and design classes. 40 premium sheets.",
        image_url: "/images/products/stationery/exercise_books.png",
        status: "active",
        stock_quantity: 680,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "A4 Graph Paper Pads (50 sheets)",
        author: "Oxford",
        isbn: "OXF-A4-GRAPH-2024",
        price: 280.00,
        category: "stationery",
        subcategory: "specialty",
        description: "A4 graph paper pads for mathematics, science diagrams, and technical drawing.",
        image_url: "/images/products/stationery/exercise_books.png",
        status: "active",
        stock_quantity: 320,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Teachers' Record Book A4",
        author: "School Pride",
        isbn: "SCH-TEACH-REC-2024",
        price: 450.00,
        category: "stationery",
        subcategory: "administrative",
        description: "Comprehensive record book for teachers with attendance and marks sections.",
        image_url: "/images/products/stationery/exercise_books.png",
        status: "active",
        stock_quantity: 150,
        featured: false,
        created_at: new Date().toISOString()
    },

    // ====== DIARIES & PLANNERS ======
    {
        title: "Student Academic Diary 2024",
        author: "Academic Planners Ltd",
        isbn: "ACA-DIARY-STU-2024",
        price: 380.00,
        category: "stationery",
        subcategory: "diaries",
        description: "Year-long academic diary for students with term dates, planners, and notes sections.",
        image_url: "/images/products/stationery/exercise_books.png",
        status: "active",
        stock_quantity: 420,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Teachers' Lesson Planner",
        author: "Academic Planners Ltd",
        isbn: "ACA-PLAN-TCH-2024",
        price: 650.00,
        category: "stationery",
        subcategory: "diaries",
        description: "Comprehensive lesson planning diary with weekly spreads and curriculum tracking.",
        image_url: "/images/products/stationery/exercise_books.png",
        status: "active",
        stock_quantity: 180,
        featured: false,
        created_at: new Date().toISOString()
    },

    // ====== ICT ACCESSORIES ======
    {
        title: "Wireless Computer Mouse",
        author: "Logitech",
        isbn: "LOG-M150-WL-2024",
        price: 2200.00,
        category: "ict",
        subcategory: "peripherals",
        description: "Reliable wireless mouse for school computer labs. USB receiver included.",
        image_url: "/images/products/ict/wireless_mouse.png",
        status: "active",
        stock_quantity: 65,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "USB Flash Drive 32GB",
        author: "SanDisk",
        isbn: "SDK-USB32-2024",
        price: 1200.00,
        category: "ict",
        subcategory: "storage",
        description: "32GB USB flash drive for student and teacher file transfers and backups.",
        image_url: "/images/products/ict/usb_flash_drive.png",
        status: "active",
        stock_quantity: 95,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "HDMI Cable 2m",
        author: "Amazon Basics",
        isbn: "AMZ-HDMI2-2024",
        price: 850.00,
        category: "ict",
        subcategory: "cables",
        description: "High-speed HDMI cable for connecting computers to projectors and displays.",
        image_url: "/images/products/ict/hdmi_cable.png",
        status: "active",
        stock_quantity: 45,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Laptop Charging Cart (16 slots)",
        author: "Ergotron",
        isbn: "ERG-LAPCART16-2024",
        price: 85000.00,
        category: "ict",
        subcategory: "infrastructure",
        description: "Secure mobile charging cart for school laptop storage and charging.",
        image_url: "/images/products/ict/charging_cart.png",
        status: "active",
        stock_quantity: 8,
        featured: false,
        created_at: new Date().toISOString()
    },

    // ====== LABORATORY EQUIPMENT ======
    {
        title: "Microscope (Student Grade)",
        author: "Swift Microscopes",
        isbn: "SWF-M40-2024",
        price: 18500.00,
        category: "lab-equipment",
        subcategory: "biology",
        description: "Monocular microscope with 40x-400x magnification for biology classes.",
        image_url: "/images/products/lab/microscope.png",
        status: "active",
        stock_quantity: 15,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Chemistry Beaker Set (5 pieces)",
        author: "Pyrex",
        isbn: "PYR-BEAKER5-2024",
        price: 3200.00,
        category: "lab-equipment",
        subcategory: "chemistry",
        description: "Set of 5 borosilicate glass beakers (50ml to 500ml) for chemistry experiments.",
        image_url: "/images/products/lab/beakers.png",
        status: "active",
        stock_quantity: 28,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Bunsen Burner with Rubber Tubing",
        author: "SciLab Supplies",
        isbn: "SCI-BUNSEN-2024",
        price: 2800.00,
        category: "lab-equipment",
        subcategory: "chemistry",
        description: "Standard Bunsen burner with adjustable air hole and safety rubber tubing.",
        image_url: "/images/products/lab/bunsen_burner.png",
        status: "active",
        stock_quantity: 35,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Electronic Balance 500g x 0.01g",
        author: "Ohaus",
        isbn: "OHA-BAL500-2024",
        price: 12500.00,
        category: "lab-equipment",
        subcategory: "general",
        description: "Precision electronic balance for chemistry and physics measurements.",
        image_url: "/images/products/lab/electronic_balance.png",
        status: "active",
        stock_quantity: 12,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Physics Optics Kit",
        author: "Edulab",
        isbn: "EDU-OPTICS-2024",
        price: 9800.00,
        category: "lab-equipment",
        subcategory: "physics",
        description: "Complete optics set including lenses, mirrors, and light source for physics experiments.",
        image_url: "/images/products/lab/physics_optics_kit.png",
        status: "active",
        stock_quantity: 18,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        title: "Human Skeleton Model (170cm)",
        author: "Anatomy Warehouse",
        isbn: "ANA-SKEL-170-2024",
        price: 32500.00,
        category: "lab-equipment",
        subcategory: "biology",
        description: "Life-sized human skeleton model on rolling stand for biology classroom.",
        image_url: "/images/products/lab/human_skeleton.png",
        status: "active",
        stock_quantity: 6,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Test Tube Rack with 12 Tubes",
        author: "Pyrex",
        isbn: "PYR-TSTRACK-2024",
        price: 1800.00,
        category: "lab-equipment",
        subcategory: "chemistry",
        description: "Wooden test tube rack with 12 borosilicate test tubes for chemistry experiments.",
        image_url: "/images/products/lab/test_tube_rack.png",
        status: "active",
        stock_quantity: 42,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Safety Goggles (Class Pack of 30)",
        author: "Uvex",
        isbn: "UVX-GOG30-2024",
        price: 4500.00,
        category: "lab-equipment",
        subcategory: "safety",
        description: "Class set of 30 chemical splash goggles for laboratory safety.",
        image_url: "/images/products/lab/safety_goggles.png",
        status: "active",
        stock_quantity: 25,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Magnifying Glass Set (3 pieces)",
        author: "Educational Insights",
        isbn: "EI-MAG3-2024",
        price: 950.00,
        category: "lab-equipment",
        subcategory: "general",
        description: "Set of 3 magnifying glasses with different magnification levels for elementary science.",
        image_url: "/images/products/lab/magnifying_glass_set.png",
        status: "active",
        stock_quantity: 60,
        featured: false,
        created_at: new Date().toISOString()
    },
    {
        title: "Lab Coat (Student Size)",
        author: "SciGuard",
        isbn: "SCI-COAT-STU-2024",
        price: 2200.00,
        category: "lab-equipment",
        subcategory: "safety",
        description: "White cotton lab coat with button front for student laboratory use.",
        image_url: "/images/products/lab/lab_coat.png",
        status: "active",
        stock_quantity: 85,
        featured: false,
        created_at: new Date().toISOString()
    }


];

async function seedProducts() {
    console.log(`Starting seed process for ${products.length} products...`);

    // Simple validation log
    const sample = products[0];
    console.log("Sample product keys:", Object.keys(sample).join(", "));

    try {
        const { data, error } = await supabase
            .from('books')
            .upsert(products, { onConflict: 'isbn' })
            .select();

        if (error) {
            throw error;
        }

        console.log("------------------------------------------");
        console.log(`✅ Success! Inserted ${data.length} products.`);
        console.log("------------------------------------------");
        data.forEach(p => {
            console.log(`- ${p.title} ($${p.price})`);
        });

    } catch (err) {
        console.error("❌ Error seeding products:", err.message);
    }
}

seedProducts();
